### ISSUE TITLE
Login persistence to containerized action steps

### ISSUE THREAD

**Issue by fagiani** [aws-actions/amazon-ecr-login#119]
Hi, I am using a step after using `aws-actions/amazon-ecr-login@v1` called `mamezou-tech/buildpacks-action@master` ro build and push the image to ECR, and as they use a Dockerfile to run the step within a container, the docker connection session is not persisted.

Is there a way to make it work? What could be done to have other "dockerized" steps to be able to benefit from the docker login action?

Thanks!

**Comment by arjraman** [comment]
I don't think it would be possible unless the action you're using allows you to input credentials to login to your registry, which it doesn't look like it does.
