### ISSUE TITLE
Cannot push with suggested permissions

### ISSUE THREAD

**Issue by cameron-martin** [aws-actions/amazon-ecr-login#14]
With the suggested permissions for pushing, I get an error `Error parsing HTTP response: unexpected end of JSON input: ""`. It seems that pushing also needs the `ecr:BatchCheckLayerAvailability` permission. See https://github.com/moby/moby/issues/19010#issuecomment-168724692

**Comment by clareliguori** [comment]
Thanks for reporting this!

**Comment by aqabawe** [comment]
Shouldn't those also include `ecr:GetAuthorizationToken on resource: *`?
