### ISSUE TITLE
Could Not Login Error

### ISSUE THREAD

**Issue by abhinav-tripathy** [aws-actions/amazon-ecr-login#205]
Not sure what I am doing wrong, but getting this error while running github actions in an ubuntu based self hosted runner on AWS. 

![image](https://user-images.githubusercontent.com/83739975/134566625-0759662a-3f48-4749-8ba2-896b0bddd781.png)

**Comment by abhinav-tripathy** [comment]
I just fixed it by doing this
```
aws ecr get-login-password --region ${{ env.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
```

**Comment by rpm-kevin** [comment]
I also received this error.  Where are you placing that "aws acr get-login-password" command in the GitHub workflow?
