### ISSUE TITLE
Push Helm Packages to ECR

### ISSUE THREAD

**Issue by vkemthur-luna** [aws-actions/amazon-ecr-login#244]
https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html
ECR allows Helm packages - but needs `helm registry login` instead of docker login.

Is there any way to get this going? Looks like `docker login` is done by default in `index.js`

**Comment by sbkg0002** [comment]
The would be great!

**Comment by prashil-sophos** [comment]
+1

**Comment by eloyred** [comment]
+1

**Comment by joodlehammond** [comment]
+1
