### ISSUE TITLE
Building Image from ECR Cache

### ISSUE THREAD

**Issue by ChristianBell1995** [aws-actions/amazon-ecr-login#26]
I was reading this about caching dependencies in Github actions workflows: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows

Is there an equivalent caching technique for building Docker images to ECR so that not all of the dependencies have to be built every time?

**Comment by clareliguori** [comment]
`docker build` supports using an existing image as a "cache", which can be pulled from a docker registry like ECR.  See this example: https://github.com/aws/aws-codebuild-docker-images/issues/26#issuecomment-370177343

Note that it can be challenging to use with multi-stage docker builds, see comments here: https://github.com/docker/docker.github.io/issues/8531

This would be a neat GitHub Action if anyone is interested in building it!
