### ISSUE TITLE
Cannot access Docker Password nor Username

### ISSUE THREAD

**Issue by ismail44** [aws-actions/amazon-ecr-login#267]
According to the docs one should be able to access the docker username/password using the prefix `docker_username` and `docker_password` (with a "cleaned" suffix with the registry URL), however they don't seem to be being set. I look at the code and I see the output, however, when I dump the step's outputs the values are not there. 

I enabled Debugging and I can confirm they are not being set:

```
##[debug]Evaluating condition for step: 'Amazon ECR "Login" Action for GitHub Actions'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Amazon ECR "Login" Action for GitHub Actions
##[debug]Register post job cleanup for action: aws-actions/amazon-ecr-login@v1
##[debug]Loading inputs
##[debug]Loading env
Run aws-actions/amazon-ecr-login@v1
##[debug]Requesting auth token for 1 registries:
##[debug]  '***'
::set-output name=registry::***.dkr.ecr.us-east-1.amazonaws.com
##[debug]steps.ecr_login.outputs.registry='***.dkr.ecr.us-east-1.amazonaws.com'
::save-state name=registries::***.dkr.ecr.us-east-1.amazonaws.com
##[debug]Save intra-action state registries = ***.dkr.ecr.us-east-1.amazonaws.com
##[debug]'skip-logout' is  for 1 registries.
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Amazon ECR "Login" Action for GitHub Actions
```

I am using the following:

```
      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v1
        id: ecr_login
        with:
          registries: "xxxxxxxxxxxx"
```

**Comment by aereal** [comment]
The feature is introduced by https://github.com/aws-actions/amazon-ecr-login/pull/191 but it is not yet released.
In other words, no Git tag exists that contains the commits.

GitHub Actions's version specification is just a Git reference.
So you can use the feature by specifying a version such as `uses: aws-actions/amazon-ecr-login@4831715c8c81dbf2ae795f9e285de2a9ee1150b4`.

**Comment by mjohnston-vtx** [comment]
Maybe I'm not using it correctly, but when I try to get the username/password, I get the following error:
`The workflow is not valid. .github/workflows/checkmarx-scanning.yaml (Line: 20, Col: 21): Unexpected symbol: '000000000000_dkr_ecr_us_east_1_amazonaws_com_docker_username'.`  
  
I guess this is because you can't start a variable name with a number? Am I misreading the format for the Docker credential output?

**Comment by Ewande** [comment]
@mjohnston-vtx it should actually be the other way round like `docker_password_000000000000_dkr_ecr_us_east_1_amazonaws_com`. 

As for the original issue, with the recent release of v1.4.0 this action can now be used without the commit hash
