### ISSUE TITLE
Update AWS SDK to v3?

### ISSUE THREAD

**Issue by berviantoleo** [aws-actions/amazon-ecr-login#272]
How about updating AWS SDK to v3?

I suggest doing this with #116 .

I am happy to help. I hope this Action will be active.

**Comment by ErikSchierboom** [comment]
We've recently been getting deprecation warnings:

> Run aws-actions/amazon-ecr-login@2f9f10ea3fa2eed41ac443fee8bfbd059af2d0a4
> (node:1659) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
> 
> Please migrate your code to use AWS SDK for JavaScript (v3).
> For more information, check the migration guide at https://a.co/7PzMCcy

Is this upgrade planned?

**Comment by saurabh-ri** [comment]
@berviantoleo Can you please fix the conflicts ?

**Comment by berviantoleo** [comment]
Resolved the conflicts
