### ISSUE TITLE
[QUESTION] Custom build args

### ISSUE THREAD

**Issue by Duardaum** [aws-actions/amazon-ecr-login#314]
There is a way to pass to docker build, custom build args?
I've trying pass build args to dockerfile, and just only the env vars that are in documentation are acceptable.

(Sorry for posting in this place..)

**Comment by arjraman** [comment]
This action doesn't support building Docker images. To do 'docker build' in conjunction with this action, see the examples [here](https://github.com/aws-actions/amazon-ecr-login#example-of-usage) in the README. If you want to use an GitHub Action to build and push, I would recommend using [docker/build-push-action](https://github.com/docker/build-push-action).
