### ISSUE TITLE
Usage of `set-output` command is deprecated

### ISSUE THREAD

**Issue by codingspirit** [aws-actions/amazon-ecr-login#371]
A warning will be generated when use this action:

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

We should avoid use `core.setOutput` and output to `$GITHUB_OUTPUT` instead

https://github.com/aws-actions/amazon-ecr-login/blob/261a7de32bda11ba01f4d75c4ed6caf3739e54be/index.js#L111

**Comment by Tomas2D** [comment]
Hello, do you plain to do it in the near future?
