### ISSUE TITLE
Cache Login Info in a job for the rest of all the following ones

### ISSUE THREAD

**Issue by MemphisMeng** [aws-actions/amazon-ecr-login#379]
I need to use AWS ECR resources in multiple jobs by logging in with the same AWS credentials. So it will be wonderful if I can do it once and let the workflow memorize my login info temporarily until all jobs are executed. So is it possible?

**Comment by arjraman** [comment]
Since each job is executed on different machines, you would have to use the login action in each job. You can use your [outputted credentials](https://github.com/aws-actions/amazon-ecr-login#docker-credentials) to login again if you prefer.
