### ISSUE TITLE
Add support for HTTP_PROXY and HTTPS_PROXY

### ISSUE THREAD

**Issue by BUDD001** [aws-actions/amazon-ecr-login#416]
While HTTP_PROXY and HTTPS_PROXY are supported in the configure-aws-credentials action, it is not supported in the ECR login.
So ECR login is currently not possible on a runner which is hosted behind a Proxy.

**Comment by flaviusLinus** [comment]
any news over here? @BUDD001 @bithavoc @stschulte @hyandell

**Comment by arjraman** [comment]
PR has been merged.
