### ISSUE TITLE
Use `setSecret()` for the generated `password`

### ISSUE THREAD

**Issue by esuarez-n26** [aws-actions/amazon-ecr-login#425]
Hey there! 👋 

In order to make the Action more secure, wouldn't it be better to use the `core.setSecret()` method from the `@actions/core` package for the token. Otherwise, the generated token can be easily leaked into the Job logs and visible from the UI, as it's set as an `output`, which could be a security risk. I think it would be better to have the token masked to avoid these kind of situations.

**Comment by arjraman** [comment]
So the `setSecret` method prevents the outputting of credentials to other jobs via `outputs`. The credentials are not printed in logs unless explicitly specified by the user or by the user setting the output mode to debug.

**Comment by esuarez-n26** [comment]
Oh, I see... I understand then, that outputting the value is the only way to make use of the information in a different job and that's the reason for not setting it as a secret?
