### ISSUE TITLE
Upgrade AWS SDK from v2 to v3 

### ISSUE THREAD

**Issue by charlesoconor** [aws-actions/amazon-ecr-login#445]
**Describe the bug**
```
We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
```

When running the action this warning is printed and says that the library will be put into maintenance mode so would be good to ensure this plugin gets sec and other updates and will continue to work in the future.

**Comment by Abdullah-Shahen** [comment]
I think #436 is taking care of this migration.

**Comment by saurabh-ri** [comment]
@arjraman Can you please merge the PR for this one ?
https://github.com/aws-actions/amazon-ecr-login/pull/436

**Comment by alexander-schreiner** [comment]
Duplicates https://github.com/aws-actions/amazon-ecr-login/issues/272
