### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by sjelisonI** [aws-actions/amazon-ecr-login#461]
**Describe the bug**
After the 1.6.1 release, our workflow call began giving this error:
Run aws-actions/amazon-ecr-login@v1
Setting proxy from environment: http://*************/
Error: connect ETIMEDOUT 44.213.61.252:443

**To Reproduce**
1. Create a composite action as follows:
  runs:
  using: "composite"
  steps:
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
3. Create a workflow that uses the composite action
4. Set http_proxy and https_proxy environment variables on the system that will be running the workflow (or set the proxy using the "http-proxy" input in the composite action)
5. Run the workflow
6. See error

**Expected behavior**
No error connect ETIMEDOUT

**Desktop (please complete the following information):**
 - OS: Amazon Linux 2023
 - Version: 6.1.29-47.49.amzn2023.x86_64
 - Amazon Linux 2023 AMI 2023.0.20230607.0 x86_64 HVM kernel-6.1

**Additional context**
- Switching to **uses: aws-actions/amazon-ecr-login@v1.6.0** resolves the issue, so it seems to be something introduced in 1.6.1.
- The IP listed in the error message seems to correspond to this DNS A record: ec2-44-213-61-252.compute-1.amazonaws.com

**Comment by BUDD001** [comment]
We are running into the exact same issue

**Comment by sjelisonI** [comment]
> Does it only run into this issue when using a proxy?

Probably, based on the "connect ETIMEDOUT" part or the error message, but I haven't tried _without_ a proxy.

**Comment by sjelisonI** [comment]
Thank you!
