### ISSUE TITLE
Certification on GitHub Marketplace

### ISSUE THREAD

**Issue by gsuess** [aws-actions/amazon-ecr-login#484]
We have a policy that doesn't allow us to use uncertified GitHub-actions, meaning that the only way we could use this action is by creating a fork first.

Could please get this certified as you did with your other actions?

**Comment by arjraman** [comment]
<img width="348" alt="Screenshot 2023-07-31 at 3 39 29 PM" src="https://github.com/aws-actions/amazon-ecr-login/assets/65422301/07c5d2d8-0056-49f5-b4d4-6acb16c11afb">
Hey @gsuess, is this action not certified?

**Comment by gsuess** [comment]
You are right. My bad. I mixed up the two. 

It is verification that we need, not certification.
