### ISSUE TITLE
Node16 Deprecation

### ISSUE THREAD

**Issue by kinano** [aws-actions/amazon-ecr-login#512]
Node16 will be deprecated on 09/11/2023 ([link](https://nodejs.org/en/blog/announcements/nodejs16-eol)). 

Node 16 is used by the action at the moment according to the source code: https://github.com/aws-actions/amazon-ecr-login/blob/865664b3240e20b35d3528593d496632704f48af/action.yml#L43-L44

Is there a plan to release a node version update soon?

**Comment by arjraman** [comment]
@kinano Node version updated

**Comment by kinano** [comment]
Thanks a billion @arjraman
