### ISSUE TITLE
Release v2 to enable the documented usage to work

### ISSUE THREAD

**Issue by nopcoder** [aws-actions/amazon-ecr-login#531]
**Describe the bug**

[The documentation describes the use of v2](https://github.com/aws-actions/amazon-ecr-login/blob/main/README.md)

**To Reproduce**
Using `aws-actions/amazon-ecr-login@v2` fail with version not found

**Expected behavior**
Release v2 to enable working with `aws-actions/amazon-ecr-login`

**Screenshots**
<img width="868" alt="image" src="https://github.com/aws-actions/amazon-ecr-login/assets/8110/1f216529-ef84-48c4-8847-69a44e7225a7">

**Desktop (please complete the following information):**
 - OS: ubuntu-latest
 - Version 2

**Comment by bithavoc** [comment]
this makes no sense /cc @arjraman

**Comment by marcosnils** [comment]
Having the same issue here. `v2` tag doesn't effectively exist.

**Comment by arjraman** [comment]
Apologies, v2 version has now been released.

**Comment by nopcoder** [comment]
Thanks 👍
