### ISSUE TITLE
Provide the ECR username and password as outputs

### ISSUE THREAD

**Issue by jarshwah** [aws-actions/amazon-ecr-login#65]
I want to use this action in combination with https://github.com/aevea/action-kaniko specifically so I can build my image with kaniko and then push it to two separate container registries (staging and production - separate registries in separate AWS accounts).

The kaniko builder requires the authentication details as it handles the registry authentication rather than using the docker login that this action provides.

I have had some success with https://github.com/elgohr/ecr-login-action to get the credentials out and pass to the kaniko builder, but I'd prefer to use this action if possible.

**Comment by Karim0928** [comment]
>

**Comment by kevzettler** [comment]
Same here. after pushing the image to ECR I need an additional step that pulls it on another machine that needs to login with the same creds

**Comment by dezren39** [comment]
i would like to use my ecr containers using the private repo feature of service containers, is there some way to provide an action which updates a secret that the service containers can use? i dont want to have to make them public
